Reindent

diff --git a/debian/init-script-template b/debian/init-script-template
--- a/debian/init-script-template
+++ b/debian/init-script-template
@@ -33,60 +33,60 @@ fi
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
 do_start() {
-    STARTED=
-    for CONF_FILE in /etc/swift/${CONFIG}.conf /etc/swift/${CONFIG}/*.conf ; do
-        if [ ! -e "$CONF_FILE" ] ; then
-            continue
-        fi
+	STARTED=
+	for CONF_FILE in /etc/swift/${CONFIG}.conf /etc/swift/${CONFIG}/*.conf ; do
+		if [ ! -e "$CONF_FILE" ] ; then
+			continue
+		fi
 
-        SUFFIX=${CONF_FILE#/etc/swift/$CONFIG}
-        SUFFIX=${SUFFIX%.conf}
-        if [ "$SUFFIX" ] ; then
-            # /etc/swift/${NAME}/*.conf
-            SUFFIX=-${SUFFIX#/}
-        fi
-        PIDFILE=/var/run/${PROJECT_NAME}/${NAME}${SUFFIX}.pid
+		SUFFIX=${CONF_FILE#/etc/swift/$CONFIG}
+		SUFFIX=${SUFFIX%.conf}
+		if [ "$SUFFIX" ] ; then
+			# /etc/swift/${NAME}/*.conf
+			SUFFIX=-${SUFFIX#/}
+		fi
+		PIDFILE=/var/run/${PROJECT_NAME}/${NAME}${SUFFIX}.pid
 
-        start-stop-daemon \
-            --start \
-            --quiet \
-            --background \
-            --chuid ${SYSTEM_USER}:${SYSTEM_GROUP} \
-            --make-pidfile \
-            --pidfile ${PIDFILE} \
-            --chdir /var/lib/${PROJECT_NAME} \
-            --startas $DAEMON \
-            --test > /dev/null \
-            || return 1
-        start-stop-daemon \
-            --start \
-            --quiet \
-            --background \
-            --chuid ${SYSTEM_USER}:${SYSTEM_GROUP} \
-            --make-pidfile \
-            --pidfile ${PIDFILE} \
-            --chdir /var/lib/${PROJECT_NAME} \
-            --startas $DAEMON \
-            -- $CONF_FILE \
-            || return 2
+		start-stop-daemon \
+			--start \
+			--quiet \
+			--background \
+			--chuid ${SYSTEM_USER}:${SYSTEM_GROUP} \
+			--make-pidfile \
+			--pidfile ${PIDFILE} \
+			--chdir /var/lib/${PROJECT_NAME} \
+			--startas $DAEMON \
+			--test > /dev/null \
+			|| return 1
+		start-stop-daemon \
+			--start \
+			--quiet \
+			--background \
+			--chuid ${SYSTEM_USER}:${SYSTEM_GROUP} \
+			--make-pidfile \
+			--pidfile ${PIDFILE} \
+			--chdir /var/lib/${PROJECT_NAME} \
+			--startas $DAEMON \
+			-- $CONF_FILE \
+			|| return 2
 
-        STARTED=1
-    done
+		STARTED=1
+	done
 
-    if [ ! "$STARTED" ] ; then
-        return 2
-    fi
+	if [ ! "$STARTED" ] ; then
+		return 2
+	fi
 }
 
 do_stop() {
-    for PIDFILE in /var/run/${PROJECT_NAME}/${NAME}*.pid ; do
-        start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
-        RETVAL=$?
-        rm -f $PIDFILE
-        if [ "$RETVAL" != "0" ] ; then
-            return "$RETVAL"
-        fi
-    done
+	for PIDFILE in /var/run/${PROJECT_NAME}/${NAME}*.pid ; do
+		start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
+		RETVAL=$?
+		rm -f $PIDFILE
+		if [ "$RETVAL" != "0" ] ; then
+			return "$RETVAL"
+		fi
+	done
 }
 
 case "$1" in
@@ -116,15 +116,15 @@ restart|force-reload)
 	log_daemon_msg "Restarting $DESC" "$NAME"
 	do_stop
 	case $? in
-        0|1)
-            do_start
-            case $? in
-                0) log_end_msg 0 ;;
-                1) log_end_msg 1 ;; # Old process is still running
-                *) log_end_msg 1 ;; # Failed to start
-            esac
-        ;;
-        *) log_end_msg 1 ;; # Failed to stop
+		0|1)
+			do_start
+			case $? in
+				0) log_end_msg 0 ;;
+				1) log_end_msg 1 ;; # Old process is still running
+				*) log_end_msg 1 ;; # Failed to start
+			esac
+		;;
+		*) log_end_msg 1 ;; # Failed to stop
 	esac
 ;;
 *)
